import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const minefont = localFont({
  src: "./minecraft_font.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={minefont.className}>
      <body>{children}</body>
    </html>
  );
}
